import { useRouter } from 'next/router'
import withAuth from '../../helpers/withAuth'
import firebase from "firebase/app";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { useEffect, useState } from "react";
import Loader from "../Components/Loader";
import styled from "styled-components";

// -----------style
const Logo = styled.p`
  font-size: 37px;
  font-family: Oswald;
  font-style: normal;
  font-weight: normal;
  line-height: 67px;
  color: lightgrey;
`;
const Home = styled.div`
  background-image: url("/Bg_Template1.jpg");
  min-height: 60vh;
  width: 100%;
  background-repeat: no-repeat;
  -webkit-background-size: cover;
  -moz-background-size: cover;
  -o-background-size: cover;
  background-size: cover;
  background-position: center;
`;
const Restname = styled.p`
  font-family: Oswald;
  font-style: normal;
  font-weight: 500;
  font-size: 80px;
  line-height: 100px;
  text-align: center;
  letter-spacing: -0.015em;
  color: white;
`;
const Restdescr = styled.p`
  margin-top: 30px;
  margin-bottom: 30px;
  font-family: Oswald;
  font-style: normal;
  font-weight: normal;
  font-size: 40px;
  text-align: center;
  color: white;
`;
const Items = styled.div`
  background: #e5e5e5;
  padding: 20px 0px 20px 0px;
`;
const Box = styled.div`
  margin-top: 30px;
  background: #ffffff;
  border-radius: 25px;
  padding: 20px 30px 20px 30px;
`;
const Itemname = styled.p`
  font-family: Oswald;
  font-style: normal;
  font-weight: normal;
  font-size: 30px;
  line-height: 30px;
`;
const Itemprice = styled.p`
  font-family: Oswald;
  font-style: normal;
  font-weight: 300;
  font-size: 25px;
  line-height: 30px;
  letter-spacing: -0.015em;
  color: #7d8491;
`;
const Itemdescr = styled.p`
  font-family: Oswald;
  font-style: normal;
  font-weight: 300;
  font-size: 20px;
  line-height: 32px;
  color: #7d8491;
`;
const Button = styled.button`
  margin-top: 30px;
  background: #c4c4c4;
  box-shadow: 0px 4px 4px rgba(0, 0, 0, 0.25);
  border: none;
  border-radius: 25px;
  font-family: Oswald;
  font-style: normal;
  font-weight: normal;
  font-size: 22px;
  line-height: 33px;
  text-align: center;
  color: #000000;
  padding: 0px 15px 0px 15px;
`;
const Footer = styled.div`
  background: #c4c4c4;
  padding: 40px 0px 40px 0px;
`;
const Location = styled.p`
  font-family: Oswald;
  font-style: normal;
  font-weight: 500;
  font-size: 40px;
  line-height: 20px;
  text-align: center;
  color: #000000;
`;
const Address = styled.p`
  font-family: Oswald;
  font-style: normal;
  font-weight: 300;
  font-size: 25px;
  line-height: 50px;
  text-align: center;
  color: #000000;
  margin-top: 20px;
`;



function Usermain(){
  const router = useRouter();
  const restname = router.query
  function signOut() {
    // [START auth_sign_out]
    firebase
      .auth()
      .signOut()
      .then(() => {
        // currentUser();
        // Sign-out successful.
      })
      .catch((error) => {
        // An error happened.
      });
    // [END auth_sign_out]
  }
  return (
    <div>
    <button onClick={signOut}>Sign Out</button>
    <Head>
      <title>Babitz</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
      <script
        async
        src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"
      ></script>
      <script
        async
        src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"
      ></script>
    </Head>
    <Home>
      <div className="container">
        <div style={{ marginTop: "20px" }}>
          <Logo>
            LOGO
          </Logo>

        </div>
        <div className="row">
          <div className="col-sm-6">
            <Restname>
          Babitz
            </Restname>
            <Restdescr>

              Somthing
            </Restdescr>
          </div>
        </div>
      </div>
    </Home>
    <Items>
      <div className="container" style={{height:'70vh', overflow:'auto'}}>
        <div className="row">
          <div className="col-sm-1"></div>
          <div className="col-sm-10">
            <Box>
              <div className="row">
                <div className="col-sm-8">
                  <Itemname>Item -1</Itemname>
                  <Itemprice>₹ 250</Itemprice>
                  <Itemdescr>
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit.
                    Phasellus quis ante aliquam, viverra arcu nec, feugiat
                    sapien. Proin mollis lorem id purus suscipit, ac tempus
                    enim pulvinar.
                  </Itemdescr>
                </div>
                <div className="col-sm-4">
                  <div style={{ float: "right" }}>
                    <Image
                      src="/Image_Item1.png"
                      layout="intrinsic"
                      width="150px"
                      height="150px"
                      alt=""
                    />
                  </div>
                </div>
              </div>
            </Box>
            <Box>
              <div className="row">
                <div className="col-sm-8">
                  <Itemname>Item -2</Itemname>
                  <Itemprice>₹ 250</Itemprice>
                  <Itemdescr>
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit.
                    Phasellus quis ante aliquam, viverra arcu nec, feugiat
                    sapien. Proin mollis lorem id purus suscipit, ac tempus
                    enim pulvinar.
                  </Itemdescr>
                </div>
                <div className="col-sm-4">
                  <div style={{ float: "right" }}>
                    <Image
                      src="/Image_Item2.png"
                      layout="intrinsic"
                      width="150px"
                      height="150px"
                      alt=""
                    />
                  </div>
                </div>
              </div>
            </Box>
            <Box>
              <Itemdescr>
                * You can add inventory from the Dashboard when you proceed.
              </Itemdescr>
            </Box>
          </div>
          <div className="col-sm-1"></div>
        </div>
      </div>
    </Items>
    <Footer>
      <Location>Location</Location>
      <Address>
        Something
      </Address>
    </Footer>
    </div>
  )
}
export default withAuth(Usermain);
