import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import withAuth from "../../helpers/withAuth";
import firebase from "firebase/app";
import { useEffect, useState } from "react";
import Loader from "../Components/Loader";
import styled from "styled-components";
import styles from "../../styles/chooseTemplate.module.css";
import { useRouter } from "next/router";

//---------styling-starts----------

const Navbar = styled.div`
  width: 100%;
  height: 250px; /* as the half of the width */
  background-color: #ffc535;
  border-bottom-left-radius: 50%; /* 100px of height + 10px of border */
  border-bottom-right-radius: 50%; /* 100px of height + 10px of border */
`;

const Heading1 = styled.p`
  text-align: center;
  font-family: "Oswald";
  font-style: normal;
  font-weight: bold;
  font-size: 40px;
  line-height: 59px;
  text-align: center;
  letter-spacing: 0.07em;
`;

const Input = styled.input`
  display: none;
  @media (max-width: 768px) {
    /* display:block; */
  }
`;
const Box = styled.div`
  margin-top: -400px;
  @media (max-width: 992px) {
    margin-top: 100px;
  }
`;
const Template_name = styled.p`
  font-family: Oswald;
  font-style: normal;
  font-weight: 500;
  font-size: 65px;
  line-height: 40px;
  letter-spacing: 0.03em;
  color: grey;
  text-shadow: 0px 0px 6.5px rgba(0, 0, 0, 0.25);
`;
const Template_descr = styled.p`
  font-family: Oswald;
  font-size: 33px;
  margin-top: 40px;
  /* text-align: justify; */

  color: #000000;
`;

const Button = styled.div`
  background: #ffc535;
  float: right;
  margin-top: -120px;
  padding: 15px;
  border-top-left-radius: 50px;
  border-bottom-left-radius: 50px;
  cursor: pointer;
  font-family: Oswald;
  font-size: 25px;
  color: #000000;
  @media (max-width: 650px) {
    margin-top: 0px;
  }
`;
//---------styling-ends----------

function ChooseTemplate() {
  const router = useRouter();
  const [template_id, setTemplate_id] = useState("1");
  const [template_name, setTemplate_name] = useState("Template 1");
  const [template_descr, setTemplate_descr] = useState(
    "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc sit amet quam ac mi"
  );
  const user = firebase.auth().currentUser;

  const choose_Template = (event) => {
    let value = event.target.value;
    setTemplate_id(value);
    if (value == 1) {
      setTemplate_name("Template 1");
      setTemplate_descr(
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc sit amet quam ac mi"
      );
    } else if (value == 2) {
      setTemplate_name("Template 2");
      setTemplate_descr(
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc sit amet quam ac mi"
      );
    } else if (value == 3) {
      setTemplate_name("Coming Soon");
      setTemplate_descr(
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit."
      );
    }
  };

  const save_Template = () => {
    if (template_id != 3) {
      var formdata = new FormData();
      formdata["templateId"] = template_id;
      console.log(JSON.stringify(formdata));

      var requestOptions = {
        method: "PATCH",
        body: JSON.stringify(formdata),
        redirect: "follow",
        headers: {
          Accept: "application/json",
          "Content-Type": "application/json",
          Authorization: user.Aa,
        },
      };
      fetch("https://babitz-backend.herokuapp.com/myrestaurant", requestOptions)
        .then((response) => response.json())
        .then((json) => {
          console.log(json);
          router.push("/Template/editTemplate");
        })
        .catch((error) => {
          console.log(error);
        });
    } else {
      alert("This template is not avaiable currently");
    }
  };
  return (
    <div>
      <Head>
        <title>Babitz</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar>
        <svg
          style={{ margin: "20px 0px 0px 20px" }}
          width="40"
          height="40"
          viewBox="0 0 90 77"
          fill="none"
          xmlns="http://www.w3.org/2000/svg"
        >
          <path
            d="M62.088 51.6342L69.032 32.0182H62.44V28.7542H73.8V31.1862L66.568 51.4422H73.832V54.6742H62.088V51.6342Z"
            fill="black"
          />
          <path
            d="M2.952 28.7542H9.352C11.8053 28.7542 13.6827 29.2555 14.984 30.2582C16.2853 31.2609 16.936 32.9782 16.936 35.4102C16.936 36.9889 16.616 38.2262 15.976 39.1222C15.336 39.9969 14.408 40.5302 13.192 40.7222C16.1787 41.2982 17.672 43.4315 17.672 47.1222C17.672 49.6182 17.064 51.5062 15.848 52.7862C14.632 54.0449 12.8293 54.6742 10.44 54.6742H2.952V28.7542ZM9.288 39.3462C10.6533 39.3462 11.5813 39.0475 12.072 38.4502C12.584 37.8315 12.84 36.8395 12.84 35.4742C12.84 34.1515 12.5093 33.2555 11.848 32.7862C11.208 32.2955 10.1307 32.0502 8.616 32.0502H7.656V39.3462H9.288ZM9.48 51.3462C10.8667 51.3462 11.8267 51.0155 12.36 50.3542C12.8933 49.6929 13.16 48.6049 13.16 47.0902C13.16 45.5329 12.8613 44.4022 12.264 43.6982C11.688 42.9729 10.7067 42.6102 9.32 42.6102H7.656V51.3462H9.48Z"
            fill="black"
          />
          <path
            d="M1.3252 75.3485L74.6737 2.00002"
            stroke="black"
            strokeWidth="3"
          />
          <path
            d="M74.6738 75.3485L1.32533 2.00003"
            stroke="black"
            strokeWidth="3"
          />
        </svg>
        <Heading1>Pick Your Taste</Heading1>
      </Navbar>
      <div className="container" id={styles.container}>
        <Input
          className={styles.item1}
          type="radio"
          onClick={choose_Template}
          value={"1"}
          name="slider"
          id="item1"
          defaultChecked
        />
        <Input
          className={styles.item2}
          type="radio"
          onClick={choose_Template}
          value={"2"}
          name="slider"
          id="item2"
        />
        <Input
          className={styles.item3}
          type="radio"
          onClick={choose_Template}
          value={"3"}
          name="slider"
          id="item3"
        />
        <div className={styles.cards}>
          <label className={styles.card} htmlFor="item1" id={styles.song1}>
            <Image
              id={styles.img}
              layout="intrinsic"
              width="300px"
              height="400px"
              src="/Template 1.png"
              alt="song"
            />
          </label>
          <label className={styles.card} htmlFor="item2" id={styles.song2}>
            <Image
              id={styles.img}
              layout="intrinsic"
              width="300px"
              height="400px"
              src="/Template 2.jpg"
              alt="song"
            />
          </label>
          <label className={styles.card} htmlFor="item3" id={styles.song3}>
            <Image
              id={styles.img}
              layout="intrinsic"
              width="300px"
              height="400px"
              src="/Template 3.jpg"
              alt="song"
            />
          </label>
        </div>
      </div>
      <Button onClick={save_Template}>
        {" "}
        Save and Next
        <svg
          width="20"
          height="20"
          viewBox="0 0 86 132"
          fill="none"
          xmlns="http://www.w3.org/2000/svg"
        >
          <line
            x1="9.53553"
            y1="4.46447"
            x2="81.5355"
            y2="76.4645"
            stroke="black"
            strokeWidth="10"
          />
          <line
            x1="3.07255"
            y1="127.947"
            x2="75.0725"
            y2="75.9466"
            stroke="black"
            strokeWidth="10"
          />
        </svg>
      </Button>
      <div className="container">
        <div className="row">
          <div className="col-md-8"></div>
          <div className="col-md-4">
            <Box>
              <Template_name>{template_name}</Template_name>
              <Template_descr> {template_descr}</Template_descr>
            </Box>
          </div>
        </div>
      </div>
      <br />
    </div>
  );
}

export default withAuth(ChooseTemplate);
