import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import withAuth from "../../helpers/withAuth";
import firebase from "firebase/app";
import { useEffect, useState } from "react";
import Loader from "../../components/Loader";
import Sidenav from "../../components/Sidenav";
import styled from "styled-components";
import MaterialTable from "material-table";

//----------------styles

const Heading = styled.h4`
  /* margin-top:10px; */
  font-family: Oswald;
  font-style: normal;
  font-weight: normal;
  font-size: 40px;
  line-height: 50px;
  /* or 100% */
  text-align: center;
  letter-spacing: 0.03em;
  color: #4b4b60;
  cursor: pointer;
  /* border-bottom:10px solid #FBB300; */
  /* max-width: 200px; */
`;
const Label = styled.h5`
  color: #4b4b60;
  font-family: Oswald;
  letter-spacing: 3px;
  margin-top: 30px;
`;

const NormalText = styled.p`
  color: #4b4b60;
  font-family: Oswald;
  font-size: 25px;
  letter-spacing: 2px;
`;

const SubmitButton = styled.button`
  background: #ffc535;
  box-shadow: 0px 4px 4px rgba(0, 0, 0, 0.25);
  border: none;
  border-radius: 25px;
  float: left;
  margin-top: 30px;
  padding: 3px;
  width: 100%;
  color: #4b4b60;
  font-family: Oswald;
  letter-spacing: 3px;
  &:hover {
    color: #ffc535;
    background: #4b4b60;
  }
`;

function EditProfile() {
  const [rest, setRest] = useState("");
  const [restnumber, setRestnumber] = useState("");
  const [restaccount, setRestaccount] = useState("");

  const user = firebase.auth().currentUser;

  useEffect(() => {
    var requestOptions = {
      method: "GET",
      redirect: "follow",
      headers: {
        Accept: "application/json",
        "Content-Type": "application/json",
        Authorization: user.Aa,
      },
    };
    fetch("https://babitz-backend.herokuapp.com/myrestaurant", requestOptions)
      .then((response) => response.json())
      .then((json) => {
        setRest(json);
        setRestnumber(json.mobileNumber);
        setRestaccount(json.billingInfo);
      });
  }, [user.Aa]);
  const set_restnumber = (event) => {
    setRestnumber(event.target.value);
  };
  const set_restaccount = (event) => {
    setRestaccount(event.target.value);
  };
  const submit_changes = (e) => {
    e.preventDefault();
    var formdata = new FormData();
    formdata["billingInfo"] = restaccount;
    formdata["mobileNumber"] = restnumber;
    var requestOptions = {
      method: "PATCH",
      body: JSON.stringify(formdata),
      redirect: "follow",
      headers: {
        Accept: "application/json",
        "Content-Type": "application/json",
        Authorization: user.Aa,
      },
    };
    fetch("https://babitz-backend.herokuapp.com/myrestaurant", requestOptions)
      .then((response) => response.json())
      .then((json) => {
        var requestOptions1 = {
          redirect: "follow",
          headers: {
            Accept: "application/json",
            "Content-Type": "application/json",
            Authorization: user.Aa,
          },
        };
        fetch(
          "https://babitz-backend.herokuapp.com/myrestaurant",
          requestOptions1
        )
          .then((response) => response.json())
          .then((json) => {
            setRest(json);
          })
          .catch((error) => {});
      })
      .catch((error) => {});
  };
  return (
    <div>
      <Head>
        <title>Babtiz</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="container-fluid">
        <div className="row">
          <div className="col-md-3">
            <Sidenav />
          </div>
          <div className="col-md-9">
            <Heading>Edit Profile</Heading>
            <form onSubmit={submit_changes}>
              <Label>Restaurant Name</Label>
              <NormalText>{rest.name}</NormalText>
              <Label>Restaurant Email</Label>
              <NormalText>{rest.email}</NormalText>
              <Label>Website Link</Label>
              <NormalText>babitz.vercel.app/{rest.name}/login</NormalText>
              <Label>Restaurant Phone Number</Label>
              <input
                type="tel"
                pattern="^[6-9]\d{9}$"
                className="form-control"
                onChange={set_restnumber}
                defaultValue={restnumber}
                placeholder="Phone Number"
                required
              />
              <Label>Restaurant Payment Details</Label>
              <input
                type="password"
                className="form-control"
                pattern="^(?:4[0-9]{12}(?:[0-9]{3})?|5[1-5][0-9]{14})$"
                onChange={set_restaccount}
                defaultValue={restaccount}
                placeholder="Payment Details"
                required
              />
              <SubmitButton type="submit" className="form-control">
                Save Changes
              </SubmitButton>
            </form>
          </div>
        </div>
      </div>
    </div>
  );
}

export default withAuth(EditProfile);
