import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import withAuth from "../../helpers/withAuth";
import firebase from "firebase/app";
import { useEffect, useState } from "react";
import Loader from "../../components/Loader";
import Sidenav from "../../components/Sidenav";
import styled from "styled-components";
import MaterialTable from "material-table";
import Profile from "../../components/Profile";

//----------------styles

const Heading = styled.h4`
  /* margin-top:10px; */
  font-family: Oswald;
  font-style: normal;
  font-weight: normal;
  font-size: 30px;
  line-height: 50px;
  /* or 100% */
  text-align: center;
  letter-spacing: 0.03em;
  color: #4b4b60;
  cursor: pointer;
  /* border-bottom:10px solid #FBB300; */
  max-width: 200px;
`;
const Label = styled.label`
  float: left;
  color: #4b4b60;
  font-family: Oswald;
  letter-spacing: 3px;
`;
const SubmitButton = styled.button`
  background: #ffc535;
  box-shadow: 0px 4px 4px rgba(0, 0, 0, 0.25);
  border: none;
  border-radius: 25px;
  float: left;
  margin-top: 30px;
  width: 100%;
  color: #4b4b60;
  font-family: Oswald;
  letter-spacing: 3px;
  &:hover {
    color: #ffc535;
    background: #4b4b60;
  }
`;

function PaymentLogs() {
  return (
    <div>
      <Head>
        <title>Babtiz</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css"
        />
      </Head>
      <div className="container-fluid">
        <div className="row">
          <div className="col-md-3">
            <Sidenav />
          </div>
          <div className="col-md-9">
            <div style={{ paddingBottom: "20px" }}>
              <Profile />
            </div>

            <center>
              <div className="row" style={{ marginTop: "60px" }}>
                <div className="col-md-12">
                  <Label>Payment Recieved To Restaurant</Label>
                  <MaterialTable
                    style={{
                      zIndex: "0",
                      width: "95%",
                      position: "absolute",
                      borderBottom: "1px solid #B1B6C0",
                      borderLeft: "1px solid #B1B6C0",
                      borderRight: "1px solid #B1B6C0",
                      borderBottomLeftRadius: "5px",
                      borderBottomRightRadius: "5px",
                      marginTop: "50px",
                      fontFamily: "Oswald",
                      marginBottom: "50px",
                    }}
                    title="List Of All Exams"
                    columns={[
                      { title: "S.No.", field: "id" },
                      { title: "Payment Id", field: "payment_id" },
                      { title: "Payment Method", field: "payment_method" },
                      { title: "Date/Time", field: "dateTime" },
                      { title: "Amount", field: "amount" },
                    ]}
                    data={[
                      {
                        id: 1,
                        payment_id: "payment_32434",
                        payment_method: "UPI",
                        dateTime: "Thu, Jul 25, 2021",
                        amount: "₹ 10000",
                      },
                      {
                        id: 2,
                        payment_id: "payment_32435",
                        payment_method: "UPI",
                        dateTime: "Thu, Aug 5, 2021",
                        amount: "₹ 12000",
                      },
                    ]}
                    options={{
                      headerStyle: {
                        background:
                          "linear-gradient(180deg, rgba(248, 235, 209, 0.8) 28.13%, rgba(248, 235, 209, 0) 100%)",
                        color: "#4B4B60",
                        fontSize: "16px",
                        fontWeight: "Montserrat",
                      },
                      cellStyle: {
                        right: "30px",
                      },
                      toolbar: false,
                      search: false,
                      sorting: true,
                    }}
                  />
                </div>
              </div>
            </center>
          </div>
        </div>
      </div>
    </div>
  );
}

export default withAuth(PaymentLogs);
