# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Production/Deployment/Integration

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types:
      - opened
      - synchronize

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
      
    - name: Test linting
      run: npm run lint
      
    - name: Run test cases and coverage
      run: npm run test:coverage
      
    - name: Run test coverage report
      run: npm run coverage:report
      
    - name: Create build
      run: npm run build  
      
      
# Setup for preview url and deployment through vercel        
    - name: Deployment For Vercel
      uses: amondnet/vercel-action@v20
      if: github.event_name == 'pull_request'
      with:
          github-token: ${{ secrets.GITHUB_TOKEN }}      
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
   

# Setup for production on vercel      
    - name: Production For Vercel
      uses: amondnet/vercel-action@v20
      if: github.event_name == 'push'
      with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          vercel-args: '--prod '
